# Generated by Django 4.2.3 on 2024-07-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_affiliate_emailtoken_profile_delete_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='referral_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='views_balance',
            field=models.IntegerField(default=0),
        ),
    ]
